# SPDX-FileCopyrightText: © 2020 Liferay Inc. <https://liferay.com>
#
# SPDX-License-Identifier: MIT

---
# Configuration for the Semantic Pull Request bot.
# https://github.com/probot/semantic-pull-requests

allowMergeCommits: true

titleAndCommits: true
